## Project information
site_name: Unità di missione per il PNRR - Coordinamento Gestione 
site_url: https://gbrunos.github.io/pnrr/
site_description: tutto ciò che serve o quasi...sul PNRR!

## Repository
# repo_name: 
repo_url: https://github.com/GBrunos/pnrr
edit_uri: edit/main/docs/                    # disables edit button 

# Copyright
copyright: Gaetano Bruno (Dip. Funzione Pubblica, Unità di missione)


## Social Media
extra:
  disqus: mkdocs
  social:
    - icon: fontawesome/solid/file-pdf
      link: https://gbrunos.github.io/pnrr/print_page/
      name: Scarica il documento in formato PDF
    - icon: octicons/comment-discussion-16
      link: https://gbrunos.github.io/pnrr/discussions
      name: Forum sul PNRR Dip. Funzione Pubblica
    - icon: fontawesome/brands/medium
      link: https://medium.com/@gaetanobruno
      name: account Medium
    - icon: fontawesome/brands/github
      link: https://https://github.com/GBrunos/pnrr
      name: Repository GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:g.bruno@funzionepubblica.it
      name: mail to g.bruno@funzionepubblica.it
    - icon: fontawesome/solid/home
      link: https://gbrunos.github.io/pnrr/
      name: Home Page
  # analytics:
  # provider: google
  # property: usa il tuo codice


## Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.tabs
 #  - navigation.indexes
    - navigation.tabs.sticky   
    - navigation.tracking
 #  - navigation.sections      # riferimento= (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections)
 #  - navigation.expand        # riferimento= (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion)
 #  - navigation.instant       # va in conflitto con i bei grafi di mergemaid
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate       # riferimento= https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
 #  - content.tabs.link           # riferimento= https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
 #  - toc.integrate               # riferimento= https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#integrated-table-of-contents

  palette:
    - scheme: default
      primary: white           # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      accent: blue             # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Lato                            # di default = Lato
    code: Roboto Mono                     # di default = Roboto Mono
  favicon: img/PNRR.png
  icon:
    repo: fontawesome/brands/github
  logo: img/PNRR.png

## Plugins
plugins:
- search
- charts                                 # per grafici/charts con https://timvink.github.io/mkdocs-charts-plugin/
- git-revision-date-localized:           # per funzionare bisogna installare plugin relativo su gh-pages.yml (installato su questo progetto)
    type: date
    locale: it
    fallback_to_build_date: false
    enable_creation_date: false
#   enabled: true
# - mkdocstrings
# - autolinks
# - macros
- print-site:
    add_to_navigation: false
    print_page_title: 'Documentazione in formato PDF'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'Documentazione in formato PDF'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "nome_file.pdf"
    exclude:



## markdown extension
markdown_extensions:
- toc:
        permalink: ↵
        toc_depth: 3
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
        - name: vegalite                                        # per grafici/charts con https://timvink.github.io/mkdocs-charts-plugin/
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.keys
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes
- md_in_html
- tables


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
   - https://cdn.jsdelivr.net/npm/vega@5                  # per grafici/charts con https://timvink.github.io/mkdocs-charts-plugin/
   - https://cdn.jsdelivr.net/npm/vega-lite@5             # per grafici/charts con https://timvink.github.io/mkdocs-charts-plugin/
   - https://cdn.jsdelivr.net/npm/vega-embed@6            # per grafici/charts con https://timvink.github.io/mkdocs-charts-plugin/

## extra CSS
extra_css:
   - stylesheets/extra.css


## Page tree
# ogni file .md corrisponde ad una pagina web (il titolo della pagina .md deve essere uguale al titolo pagina riportato qui di sotto nel menù)
nav:
    - 🏠: index.md
    
    - Riforme:
        - Semplificazione: contenuti/catalogo.md
        - Lavoro pubblico: contenuti/catalogo.md
 
    - Investimenti: 
        - Test1: contenuti/PubblicaAmministrazione.md

    - Documenti:
        - Test2: contenuti/linkografia.md
 
