## Project information
site_name: Ciro Spataro
site_url: https://cirospat.github.io/cirospataro/
site_description: Profilo di Ciro Spataro

## Repository
# repo_name: cirospat mkdocs-style
# repo_url: https://github.com/cirospat/mkdocs-style
# edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <img src="https://img.shields.io/github/last-commit/cirospat/cirospataro.svg?&label=ultimo_aggiornamento">  <img src="https://img.shields.io/github/license/cirospat/cirospataro">

## Social Media
extra:
  manifest: "manifest.webmanifest"
  disqus: mkdocs
  social:
    - icon: fontawesome/solid/home
      link: https://cirospat.github.io/cirospataro/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/cirospat
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ciro.spataro.3
      name: facebook
    - icon: fontawesome/brands/github
      link: https://github.com/cirospat/mkdocs-style
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: editare url dell'eventuale gruppo telegram
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:cirospat@gmail.com
      name: mail to cirospat@gmail.com
    - icon: fontawesome/solid/file-pdf
      link: https://cirospat.github.io/mkdocs-style/print_page/
      name: Scarica il documento in formato PDF
  # analytics:
  # provider: google
  # property: usa il tuo codice

    
## Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
  # - toc.integrate
  
  palette:
    - scheme: default
      primary: white           # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      accent: red              # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: img/logo2.png
  icon:
    repo: fontawesome/brands/github
  logo: img/logo2.png

## Plugins
plugins:
- search
- mkdocstrings
- autolinks
- macros  
- print-site:
    add_to_navigation: false
    print_page_title: 'Documentazione in formato PDF'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'Documentazione in formato PDF'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "nome_file.pdf"
    exclude:



## markdown extension
markdown_extensions:
- toc:
        permalink: ↵
- meta        
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

## extra CSS
extra_css:
   - stylesheets/extra.css
  
## Page tree 
# ogni file .md corrisponde ad una pagina web 
nav:
    - Home: index.md
    
    - Profilo:
        - Profilo work: profilo/profilo.md
        - Opendatasicilia & communities: profilo/opendatasicilia-communities.md
        - CV: profilo/cv.md
            
    - Risorse e conoscenza:
        - Risorse e conoscenza: risorse-conoscenza/risorse-conoscenza.md
        - Tutorial manuali e corsi: risorse-conoscenza/tutorial-manuali-corsi.md
        - Mappe: risorse-conoscenza/mappe.md
        - Catalogo webinar opendata: risorse-conoscenza/catalogo-webinar-opendata.md
        - Accesso Civico: risorse-conoscenza/accesso-civico.md
        - Accessibilità: risorse-conoscenza/accessibilita.md
            
    - Comune di Palermo:
        - Open data e innovazione: comune-palermo/opendata-innovazione.md
        - Catalogo servizi online: comune-palermo/catalogo-servizi-online.md
        - Atuazione CAD: comune-palermo/attuazione-cad
        - Lavoro Agile: comune-palermo/lavoro-agile.md
        - Piano triennale informatica: comune-palermo/piano-triennale-informatica.md
            
    - Amministrazione digitale:
        - Fondamentali per la PA digitale: amministrazione-digitale/fondamentali-pa-digitale.md
        - Responsabile transizione digitale: amministrazione-digitale/rtd.md
        - Competenze digitali dipendenti: amministrazione-digitale/competenze-digitali-dipendenti.md
        - Competenze digitali cittadini: amministrazione-digitale/competenze-digitali-cittadini.md
        - Vocaborlari controllati e ontologie: amministrazione-digitale/vocabolaricontrollati-ontologie.md
        
    - Privacy | cookies: 
        - Privacy/cookies: privacy.md
