## Project information
site_name: cirospat mkdocs-style
site_url: https://cirospat.github.io/mkdocs-style/
site_description: cirospat mkdocs-style - modello di documentazione online

## Repository
# repo_name: cirospat mkdocs-style
# repo_url: https://github.com/cirospat/mkdocs-style
# edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <a href="https://cirospat.github.io/mkdocs-style/privacy/" title="Informativa privacy-cookies">Privacy-cookies</a> | <a href="https://creativecommons.org/licenses/by/4.0/deed.it" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribution 4.0 licence (CC BY)" target="_blank" class="link-dark text-decoration-none">Lic. CC-BY 4.0</a>

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/home
      link: https://cirospat.github.io/mkdocs-style/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/cirospat
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ciro.spataro.3
      name: facebook
    - icon: fontawesome/brands/github
      link: https://github.com/cirospat/mkdocs-style
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: editare url dell'eventuale gruppo telegram
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:cirospat@gmail.com
      name: mail to cirospat@gmail.com
    - icon: fontawesome/solid/rss
      link: ../feed_rss_created.xml
      name: Feed RSS
    - icon: fontawesome/solid/file-pdf
      link: https://cirospat.github.io/mkdocs-style/print_page/
      name: Scarica il file PDF
  disqus: https-cirospat-github-io-mkdocs-style
  # analytics:
  # provider: google
  # property: usa il tuo codice

    
## Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs

  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  logo: img/logo2.png

## Plugins
plugins:
- search
- mkdocstrings
- autolinks
- macros  
- print-site:
    add_to_navigation: false
    print_page_title: 'Documento formato PDF'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'documento in formato PDF'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "ODS_Mkdocs-Material.pdf"
    exclude:

## Feed RSS setting
- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false 
        datetime_format: "%d-%m-%Y"
    # datetime_format: "%Y-%m-%d"
    image: https://cirospat.github.io/mkdocs-style/img/logo2.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    match_path: ".*"
    url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"    

## markdown extension
markdown_extensions:
- toc:
        permalink: ↵
- meta        
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

## extra CSS
extra_css:
   - stylesheets/ods-extra.css
  
## Page tree 
# ogni file .md corrisponde ad una pagina web 
nav:
    - Home: index.md
    
    - Installazione:
        - Insta 1: Installazione/insta1.md
        - Insta 2:
            -  Insta 2.1: Installazione/insta2_1.md
            -  Insta 2.2: Installazione/insta2_2.md   
        - Insta 3: Installazione/insta3.md 
            
    - Configurazione:
        - Congf 1: Configurazione/conf1.md
        - Congf 2: Configurazione/conf2.md
            
    - Riferimenti:
        - Rifer 1: Riferimenti/rifer1.md
        - Rifer 2:
            - Rifer 2.1: Riferimenti/rifer2_1.md
            - Rifer 2.2: Riferimenti/rifer2_2.md 
            - Rifer 2.3: Riferimenti/rifer3_3.md 
        
    - About:
        - OpenDataSicilia: ods.md
        
    - Privacy/cookies: 
        - Privacy/cookies: privacy.md
