## Project information
site_name: Mappatura dei procedimenti amministrativi per la digitalizzazione
site_url: https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi/
site_description: Mappatura dei procedimenti amministrativi per la digitalizzazione

## Repository
repo_name: mappatura-procedimenti-amministrativi
repo_url: https://github.com/UO-TransizioneDigitaleComunePalermo/mappatura-procedimenti-amministrativi
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <img src="https://img.shields.io/github/last-commit/uo-transizionedigitalecomunepalermo/mappatura-procedimenti-amministrativi.svg?&label=ultimo_aggiornamento"> 
           <img src="https://img.shields.io/github/license/uo-transizionedigitalecomunepalermo/mappatura-procedimenti-amministrativi"> <br> 
           

## Social Media
extra:
  manifest: "manifest.webmanifest"
  disqus: mkdocs
  social:
    - icon: fontawesome/solid/home
      link: https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/cirospat
      name: account twitter
    - icon: fontawesome/brands/github
      link: https://github.com/UO-TransizioneDigitaleComunePalermo/mappatura-procedimenti-amministrativi
      name: Repoisitory GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:c.spataro@comune.palermo.it
      name: mail to c.spataro@comune.palermo.it
    - icon: fontawesome/solid/file-pdf
      link: https://uo-transizionedigitalecomunepalermo.github.io/mappatura-procedimenti-amministrativi/print_page/
      name: Scarica il documento in formato PDF
  # analytics:
  # provider: google
  # property: usa il tuo codice

    
## Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  static_templates:
    - 404.html
  language: it
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections      #prova (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections)
    - navigation.expand        #prova (https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion)
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
 #  - toc.integrate
  
  palette:
    - scheme: default
      primary: blue grey           # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      accent: red              # setting colori = https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#configuration
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: img/logo1.png
  icon:
    repo: fontawesome/brands/github
  logo: img/logo1.png

## Plugins
plugins:
- search
- mkdocstrings
- autolinks
- macros  
- print-site:
    add_to_navigation: false
    print_page_title: 'Documentazione in formato PDF'
    add_print_site_banner: true
    print_site_banner_template: "docs/pdf/banner.tpl"
    # Table of contents
    add_table_of_contents: true
    toc_title: 'Documentazione in formato PDF'
    toc_depth: 6
    # Content-related
    add_full_urls: true
    enumerate_headings: true
    enumerate_figures: true
    add_cover_page: true
    cover_page_template: "docs/pdf/cover_page.tpl"
    path_to_pdf: "nome_file.pdf"
    exclude:



## markdown extension
markdown_extensions:
- toc:
        permalink: ↵
- meta        
- mkdocs-click
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- def_list
- abbr
- pymdownx.snippets
- footnotes
- md_in_html


## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

## extra CSS
extra_css:
   - stylesheets/extra.css
  

## Page tree 
# ogni file .md corrisponde ad una pagina web 
nav:
    - Home: index.md
         
    - Focus giuridico:
        - Focus giuridico sui procedimenti: mappatura-procedimenti/4-focus-giuridico-procedimenti.md
     
    - Mappatura e analisi dei procedimenti:
        - Percorsi di digitalizzazione in ambito comuale: mappatura-procedimenti/1-percorsi-di-digitalizzazione-in-ambito-comunale.md
        - L'analisi dei procedimenti nel Piano della Performance: mappatura-procedimenti/3-esperienza-analisi-procedimenti.md 
     
    - Metadati dei procedimenti:
        - I metadati nella mappatura dei procedimenti: mappatura-procedimenti/5-metadati-procedimento.md
        - Metadati minimi di determinazioni e deliberazioni: mappatura-procedimenti/2-elementi-minimi-metadati-determinazione-deliberazione.md
        - Uno schema di metadati usato nella mappatura dei procedimenti: mappatura-procedimenti/8-schema-metadati-procedimento.md
        - Un esperienza di mappatura con metadati: mappatura-procedimenti/6-esperienza-metadatazione-procedimento.md
   
    - Cataologo dei procedimenti:
        - Dalla mappatura al catalogo dei procedimenti: mappatura-procedimenti/7-catalogo-procedimenti.md 
    
    - Linkografia:
        - Linkografia essenziale: mappatura-procedimenti/9-linkografia-essenziale.md
            
    - Chi siamo:
        - Chi siamo: mappatura-procedimenti/10-chi-siamo.md
     
    - Privacy e cookies: 
        - Privacy e cookies: privacy.md
