name: gh-deploy 


on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions>=1.0    # aggiunto il 28 nov 2021
      - run: pip install markdown>=3.2                      # aggiunto il 28 nov 2021
      - run: pip install Pygments>=2.4                      # aggiunto il 28 nov 2021
      - run: pip install requests_oauthlib
#     - run: pip install click                              # disattivato il 28 nov 2021
      - run: pip install click-plugins                      
#     - run: pip install click-config-file                  # disattivato il 28 nov 2021
#     - run: pip install pytest                             # disattivato il 28 nov 2021
#     - run: pip install mkdocs                             # disattivato il 28 nov 2021
      - run: pip install mkdocs>=1.2.2
      - run: pip install mkdocstrings                       
      - run: pip install mkdocs-click
      - run: pip install pygments
#     - run: pip install pymdown-extensions                # disattivato il 28 nov 2021
      - run: pip install pymdown-extensions>=9.0           # aggiunto il 28 nov 2021
      - run: pip install mkdocs-autolinks-plugin           
      - run: pip install mkdocs-jupyter                    # attivato abilita "content tabs" e disabilita "code annotation" 
      - run: pip install mkdocs-exclude                    # in sospeso
      - run: pip install mkdocs-exclude-search             # in sospeso 
      - run: pip install mkdocs-macros-plugin              # in sospeso 
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-pdf-export-plugin
 #    - run: pip install mkdocs-git-revision-date-localized-plugin   # disattivato il 28 nov 2021
 #    - run: pip install mkdocs-windmill                             # disattivato il 28 nov 2021
 #    - run: pip install mkdocs-img2fig-plugin                       # disattivato il 28 nov 2021
 #    - run: pip install mkdocs-rss-plugin                           # disattivato il 28 nov 2021
      - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force

# setting by https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/.github/workflows/gh-deploy.yml
